#+title: Web

* Description

The =web= storage driver allows the acquisition of data from the internet, in
particular using URLs.

* Required packages

+ Downloads (part of Julia's stdlib)

* Parameters

- url :: Path to the online data.
- headers :: HTTP headers that should be set.
- timeout :: Maximum number of seconds to try to download for before abandoning.
- cache :: Whether caching should be performed, this can be set to a file path,
  or a boolean value. When set to =true= a file path will be generated based on
  the UUID of the data set.
- cachefolder :: Folder that the =cache= file path should be expanded relative to.
  When applicable, =cachefolder= itself is expanded relative to the data TOML
  file, otherwise the current working directory is used.
- checksum :: The CRC32c checksum of the data. This also accepts a special value,
  ~"auto"~ in which case the first time the data is accessed the calculated
  checksum will be replace the ~"auto"~ value.

* Usage examples

Downloading the data on-demand each time it is accessed.

#+begin_src toml
[[iris.storage]]
driver = "web"
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
#+end_src

Adding a checksum to ensure that the data is unchanged.

#+begin_src toml
[[iris.storage]]
driver = "web"
checksum = 4155407972
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
#+end_src

Specifying a file path to cache the data at.

#+begin_src toml
[[iris.storage]]
driver = "web"
cache = "downloads/iris.csv"
checksum = 4155407972
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
#+end_src

Specifying a cache folder, with the file name generated based on the dataset
UUID.

#+begin_src toml
[[iris.storage]]
driver = "web"
cache = true
cachefolder = "downloads"
checksum = 4155407972
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
#+end_src
