name = "DataToolkitBase"
uuid = "e209d0c3-e863-446f-9b45-de6ca9730756"
version = "0.10.0"
authors = ["TEC <git@tecosaur.net>"]

[deps]
DataToolkitCommon = "9e6fccbf-6142-406a-aa4c-75c1ae647f53"
DataToolkitCore = "caac3e55-418c-402e-a061-64d454aa8f4f"
DataToolkitStore = "082ec3c2-3fb3-458f-ad22-5e5e31d4377a"

[compat]
DataToolkitCommon = "~0.10"
DataToolkitCore = "~0.10"
DataToolkitStore = "~0.10"
julia = "1"
